In [1]:
import pandas as pd

In [2]:
import numpy as np
import shapely

In [3]:
bos_addr = pd.read_csv('/Users/DavidStier/Documents/Python and Data Science/DSI Class/Final Project/Model Building/BostonAddressTest.csv')

/Applications/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
bos_addr.shape

(99073, 19)

In [5]:
bos_addr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99073 entries, 0 to 99072
Data columns (total 19 columns):
PID                99073 non-null int64
ST_NUM             99073 non-null object
STNum_nospace      88580 non-null object
STNum_noLetters    99073 non-null float64
ST_NAME            99073 non-null object
ST_NAME_SUF        98995 non-null object
ZIPCODE            99073 non-null int64
PTYPE              99073 non-null int64
LU                 99073 non-null object
OWN_OCC            99073 non-null object
AV_LAND            99073 non-null int64
AV_BLDG            99073 non-null int64
LAND_SF            99053 non-null float64
YR_BUILT           98452 non-null float64
YR_REMOD           77372 non-null float64
GROSS_AREA         98620 non-null float64
LIVING_AREA        98620 non-null float64
LATITUDE           99073 non-null float64
LONGITUDE          99073 non-null float64
dtypes: float64(8), int64(5), object(6)
memory usage: 14.4+ MB

In [6]:
bos_addr.head()

,PID,ST_NUM,STNum_nospace,STNum_noLetters,ST_NAME,ST_NAME_SUF,ZIPCODE,PTYPE,LU,OWN_OCC,AV_LAND,AV_BLDG,LAND_SF,YR_BUILT,YR_REMOD,GROSS_AREA,LIVING_AREA,LATITUDE,LONGITUDE
0,2101865020,9B,9B,0.0,MONASTERY,RD,2135,101,R1,Y,198800,215000,5421.0,1965.0,0.0,2099.0,1756.0,42.345956,-71.147305
1,1805555000,9B,9B,0.0,RAWSTON,RD,2131,106,RL,N,19900,0,1100.0,0.0,NaN,0.0,0.0,42.278469,-71.129122
2,802587010,9A -9C,9A,0.0,FAIRLAND,ST,2119,995,CM,N,0,0,4911.0,2002.0,NaN,0.0,0.0,42.325331,-71.078306
3,2101865010,9A,9A,0.0,MONASTERY,RD,2135,104,R2,Y,221600,345800,5347.0,1955.0,2002.0,2184.0,1611.0,42.345882,-71.147162
4,1805557000,9A,9A,0.0,RAWSTON,RD,2131,106,RL,N,19900,0,1100.0,0.0,NaN,0.0,0.0,42.278427,-71.129174

In [7]:
bos_addr['STNum_noLetters'].unique()

array([   0. ,  999. ,  998. , ...,  459. ,  438. ,  152.5])

In [8]:
bos_addr['block_set'] = bos_addr['STNum_noLetters'].apply(lambda x: x // 100 if x !='has_text' else 0)

In [9]:
bos_addr.tail(5)

,PID,ST_NUM,STNum_nospace,STNum_noLetters,ST_NAME,ST_NAME_SUF,ZIPCODE,PTYPE,LU,OWN_OCC,AV_LAND,AV_BLDG,LAND_SF,YR_BUILT,YR_REMOD,GROSS_AREA,LIVING_AREA,LATITUDE,LONGITUDE,block_set
99068,603765006,1,1,1.0,LAUTEN,PL,2127,101,R1,N,117500,242200,948.0,1890.0,NaN,1638.0,1092.0,42.337677,-71.028070,0.0
99069,604500000,1,1,1.0,DEAN,WY,2127,101,R1,Y,246100,382300,3400.0,1860.0,0.0,4028.0,2480.0,42.335312,-71.025804,0.0
99070,100382000,1,1,1.0,SWIFT,TE,2128,101,R1,N,144500,187900,4436.0,1900.0,0.0,1976.0,1574.0,42.380580,-71.022003,0.0
99071,100706000,1,1,1.0,MOORE,ST,2128,101,R1,Y,116000,173700,3000.0,1910.0,0.0,2198.0,1406.0,42.384232,-71.020090,0.0
99072,102236000,1,1,1.0,ORIENT,AV,2128,105,R3,N,140500,316600,3320.0,1912.0,0.0,6700.0,4428.0,42.389889,-70.998987,0.0

In [10]:
bos_addr['block_set'].unique()

array([   0.,    9.,    8.,    7.,    6.,    5.,   53.,   52.,   51.,
         50.,    4.,   49.,   48.,   47.,   46.,   45.,   44.,   43.,
         42.,   41.,   40.,   39.,    3.,   38.,   37.,   36.,   35.,
         34.,   33.,   32.,   31.,   30.,    2.,   29.,   28.,   27.,
         26.,   25.,   24.,   23.,   22.,   21.,   20.,   19.,    1.,
         18.,   17.,   16.,   15.,   14.,   13.,   12.,   11.,   10.,
        427.,  426.,  425.,  424.,  423.,  411.,  399.,  387.,  383.,
        335.,  275.,  211.,  207.,  126.])

In [11]:
bos_street_group = bos_addr.groupby(['ST_NAME','block_set'])

In [12]:
bos_street_group.median()

                                 PID  STNum_noLetters  ZIPCODE  PTYPE  \
ST_NAME      block_set
A            0.0        6.012295e+08             17.0   2127.0  390.0
             1.0        6.027425e+08            170.0   2210.0  440.0
             2.0        6.011651e+08            244.0   2127.0  390.0
             3.0        6.027340e+08            323.5   2127.0  345.0
ABBOT        0.0        1.401931e+09             22.0   2124.0  105.0
ABBOTSFORD   0.0        1.203003e+09             17.0   2121.0  104.0
ABBY         0.0        2.200633e+09             14.0   2135.0  250.5
ABERDEEN     0.0        2.100149e+09             14.0   2215.0  904.0
ACACIA       0.0        2.009567e+09             15.0   2132.0  101.0
ACADEMY HILL 0.0        2.204937e+09             32.0   2135.0  104.0
             1.0        2.204930e+09            112.0   2135.0  101.0
ACADIA       0.0        6.037260e+08             11.0   2127.0  132.0
             425.0      6.037040e+08          42560.0   2127.0  995.0
ACHORN       0.0        1.901488e+09              1.5   2130.0  549.5
ACKLEY       0.0        1.102244e+09             16.0   2130.0  979.0
ACORN        0.0        5.015265e+08              4.5   2108.0  101.0
ACTON        0.0        1.812249e+09              0.0   2136.0  132.0
ADA          0.0        1.903992e+09             18.0   2131.0  102.5
ADAIR        0.0        2.203337e+09             22.0   2135.0  104.0
ADAMS        0.0        1.501617e+09             11.0   2122.0  105.0
             1.0        1.500539e+09            158.0   2122.0  105.0
             2.0        1.501537e+09            254.0   2122.0  332.0
             3.0        1.600688e+09            363.0   2122.0  105.0
             4.0        1.601114e+09            438.0   2122.0  105.0
             5.0        1.601999e+09            564.0   2122.0  104.0
             6.0        1.603222e+09            654.0   2122.0  105.0
             7.0        1.603618e+09            742.0   2122.0  319.0
             8.0        1.605074e+09            883.5   2124.0  104.0
             9.0        1.604973e+09            933.0   2124.0  104.0
             10.0       1.703604e+09           1070.5   2124.0  104.0
...                              ...              ...      ...    ...
WORDSWORTH   1.0        1.027035e+08            145.5   2128.0  102.5
WORLEY       0.0        2.006840e+09             35.5   2132.0  101.0
WORMWOOD     0.0        6.027540e+08             21.0   2210.0  986.0
WORRELL      0.0        1.600303e+09              0.0   2122.0  504.0
WORTHINGTON  0.0        1.000036e+09             17.0   2120.0  101.0
WREN         0.0        2.002178e+09             41.5   2132.0  101.0
             1.0        2.002069e+09            142.0   2132.0  101.0
             2.0        2.002010e+09            216.5   2132.0  101.0
WRENTHAM     0.0        1.602971e+09             43.0   2124.0  101.0
             1.0        1.603130e+09            129.5   2124.0  104.0
WRIGHT       0.0        1.904058e+09              0.0   2131.0  985.0
WYCLIFF      0.0        2.009288e+09             32.5   2132.0  101.0
WYMAN        0.0        1.002688e+09             60.0   2130.0  105.0
             1.0        1.900003e+09            101.0   2130.0  104.5
WYOLA        0.0        1.400102e+09             15.0   2121.0  440.0
WYOMING      0.0        1.202050e+09             13.5   2121.0  104.0
WYVERN       0.0        1.904289e+09             24.5   2131.0  101.0
YALE         0.0        1.103778e+09             25.5   2130.0  108.0
YARMOUTH     0.0        4.006485e+08             19.0   2116.0  553.0
YAWKEY       0.0        5.043360e+08             24.0   2215.0  328.0
YEOMAN       0.0        8.021540e+08             36.0   2119.0  390.0
YORK         0.0        1.401740e+09             13.0   2121.0  105.0
YORKTOWN     0.0        2.007792e+09              7.5   2132.0  101.0
YOUNGS       0.0        1.801057e+09              0.0   2126.0  106.0
YUILL        0.0        1.809833e+09              0.0   2136.0  106.0
ZAMORA       0.0        1.002114e+09             14.0   2130.0  104.0
             425.0      1.002107e+09          42592.0   2130.0  995.0
ZEIGLER      0.0        8.025080e+08             80.0   2119.0  225.5
             1.0        8.025000e+08            131.0   2119.0  121.0
ZELLER       0.0        2.004950e+09             36.5   2131.0  101.0

                           AV_LAND     AV_BLDG  LAND_SF  YR_BUILT  YR_REMOD  \
ST_NAME      block_set
A            0.0          116000.0     34450.0   4948.5    1910.0    1991.0
             1.0          178946.0    323699.5   6373.0       0.0       NaN
             2.0         6340800.0  14408200.0  47374.0       0.0    2009.0
             3.0         2013050.0   2079200.0  12494.5    1929.0    2010.5
ABBOT        0.0          164400.0    257200.0   5595.0    1905.0       0.0
ABBOTSFORD   0.0          103700.0    217600.0   4489.0    1900.0    1980.0
ABBY         0.0          150000.0    263250.0   4954.5    1900.0     994.5
ABERDEEN     0.0          351700.0    567800.0   2472.0    1920.0    1980.0
ACACIA       0.0          126800.0    231900.0   4433.0    1935.0       0.0
ACADEMY HILL 0.0          204900.0    377300.0   4659.0    1915.0       0.0
             1.0          289800.0    555500.0  11991.0    1900.0     980.0
ACADIA       0.0           45800.0         0.0   1875.0    1905.0     999.5
             425.0             0.0         0.0   3725.0    1999.0    1999.0
ACHORN       0.0          127450.0    255700.0   4088.0    1890.0    1002.5
ACKLEY       0.0          102814.0    221627.0   3500.0    1905.0    1999.5
ACORN        0.0         1008185.0   1019250.0    822.0    1825.5    1000.0
ACTON        0.0           11400.0         0.0   2553.0       0.0       0.0
ADA          0.0          134100.0    204900.0   4277.5    1927.5       0.0
ADAIR        0.0          183802.5    390827.5   4048.5    1930.0       0.0
ADAMS        0.0          150800.0    190700.0   3942.0    1900.0    1995.0
             1.0          137500.0    264400.0   4354.0    1905.0    1977.0
             2.0          157750.0    330450.0   5943.0    1920.0    2000.0
             3.0          140900.0    237450.0   5260.0    1915.0    1990.0
             4.0          172450.0    307450.0   5949.0    1917.5    1975.0
             5.0          167800.0    278800.0   5977.0    1930.0    1991.5
             6.0          140000.0    306250.0   3589.5    1920.0    1981.0
             7.0          155000.0    325300.0   4720.0    1920.0    1991.0
             8.0          170400.0    296850.0   6411.0    1913.0       0.0
             9.0          155800.0    283000.0   5079.0    1928.0       0.0
             10.0         189450.0    296350.0   7616.0    1915.0     992.0
...                            ...         ...      ...       ...       ...
WORDSWORTH   1.0          128050.0    222800.0   2975.0    1910.0       0.0
WORLEY       0.0          152200.0    277950.0   5500.0    1930.0       0.0
WORMWOOD     0.0        12040600.0         0.0  42638.0    1900.0    2006.0
WORRELL      0.0           91100.0         0.0   8734.0       0.0       NaN
WORTHINGTON  0.0          270700.0    431000.0   1440.0    1900.0    1998.0
WREN         0.0          213650.0    326550.0   7653.0    1910.0       0.0
             1.0          190300.0    294100.0   5900.0    1930.0    1975.0
             2.0          215750.0    337450.0   7855.5    1930.0    1983.0
WRENTHAM     0.0          120100.0    250300.0   3172.0    1910.0       0.0
             1.0          156450.0    245900.0   4963.0    1926.0       0.0
WRIGHT       0.0           72000.0         0.0   4830.0       0.0       NaN
WYCLIFF      0.0          152350.0    270700.0   6660.0    1926.5       0.0
WYMAN        0.0          161200.0    486800.0   3946.0    1905.0    2001.0
             1.0          159850.0    405950.0   3403.0    1957.0    1995.0
WYOLA        0.0           35580.0         0.0   2722.0       0.0    2002.0
WYOMING      0.0          114500.0    189850.0   5250.0    1900.0       0.0
WYVERN       0.0          126315.0    227950.0   4463.5    1915.5       0.0
YALE         0.0          238200.0    249150.0  11513.0    1890.0    1999.0
YARMOUTH     0.0          289500.0    499500.0   2202.5    1899.0    1999.0
YAWKEY       0.0         2475700.0    953800.0  14043.0    1920.0    2004.0
YEOMAN       0.0           17000.0         0.0   1700.0       0.0       NaN
YORK         0.0          155900.0    233550.0   4986.0    1900.0       0.0
YORKTOWN     0.0          145450.0    266700.0   5030.0    1937.0       0.0
YOUNGS       0.0           32600.0         0.0   4000.0       0.0       NaN
YUILL        0.0           32700.0         0.0   3612.0       0.0    1002.0
ZAMORA       0.0          216200.0    453900.0   4974.0    1920.0       0.0
             425.0             0.0         0.0   7993.0    2013.0       NaN
ZEIGLER      0.0          205200.0    555900.0   6385.0     945.0    1000.5
             1.0          128600.0    373900.0   3688.0    2006.0       NaN
ZELLER       0.0          150050.0    290550.0   5053.5    1934.0       0.0

                        GROSS_AREA  LIVING_AREA   LATITUDE  LONGITUDE
ST_NAME      block_set
A            0.0               0.0          0.0  42.341738 -71.055408
             1.0               0.0          0.0  42.344786 -71.053091
             2.0               0.0          0.0  42.348394 -71.051716
             3.0           30213.0      25326.5  42.349325 -71.049288
ABBOT        0.0            6252.0       4248.0  42.296695 -71.085827
ABBOTSFORD   0.0            5579.0       3379.0  42.314517 -71.092333
ABBY         0.0            2156.0       1382.0  42.361376 -71.141963
ABERDEEN     0.0            3950.0       2365.0  42.346185 -71.103635
ACACIA       0.0            2604.0       1464.0  42.273949 -71.161206
ACADEMY HILL 0.0            4128.0       2648.0  42.346841 -71.154115
             1.0            4625.0       2880.0  42.345340 -71.155021
ACADIA       0.0               0.0          0.0  42.337792 -71.029797
             425.0             0.0          0.0  42.337820 -71.030186
ACHORN       0.0            2505.0       1525.0  42.307905 -71.116224
ACKLEY       0.0               0.0          0.0  42.311296 -71.103704
ACORN        0.0            3050.5       2214.5  42.357539 -71.068855
ACTON        0.0               0.0          0.0  42.251730 -71.139722
ADA          0.0            2674.5       1414.0  42.280901 -71.122494
ADAIR        0.0            3452.5       1830.0  42.352277 -71.166931
ADAMS        0.0            2835.0       1780.0  42.306250 -71.061878
             1.0            5478.0       3681.0  42.303432 -71.060663
             2.0            5161.0       3682.5  42.300457 -71.058966
             3.0            5509.0       2933.0  42.296954 -71.056635
             4.0            5077.5       2947.0  42.294253 -71.056786
             5.0            4419.0       2661.0  42.290541 -71.056697
             6.0            4311.5       2538.0  42.287504 -71.055023
             7.0            4480.0       2317.0  42.284213 -71.055288
             8.0            3959.0       2275.0  42.281135 -71.058531
             9.0            3834.0       2340.0  42.279364 -71.059510
             10.0           3972.0       2340.0  42.274758 -71.062089
...                            ...          ...        ...        ...
WORDSWORTH   1.0            3253.0       1931.5  42.382951 -71.014296
WORLEY       0.0            2562.0       1394.0  42.292129 -71.162403
WORMWOOD     0.0           93971.5      80547.0  42.346993 -71.049564
WORRELL      0.0               0.0          0.0  42.294060 -71.049912
WORTHINGTON  0.0            2880.0       2290.0  42.334183 -71.102195
WREN         0.0            3781.5       2225.0  42.281414 -71.151929
             1.0            2790.0       1686.0  42.279052 -71.148179
             2.0            3163.5       1783.0  42.277687 -71.146174
WRENTHAM     0.0            3565.0       2117.0  42.288071 -71.061383
             1.0            3768.0       2336.5  42.288765 -71.057378
WRIGHT       0.0               0.0          0.0  42.282607 -71.124899
WYCLIFF      0.0            2486.0       1453.0  42.276644 -71.168757
WYMAN        0.0            4281.0       2568.0  42.320646 -71.105347
             1.0            4213.5       3172.0  42.319328 -71.103789
WYOLA        0.0               0.0          0.0  42.307876 -71.074600
WYOMING      0.0            4878.0       2882.5  42.315106 -71.085160
WYVERN       0.0            2194.0       1286.0  42.288034 -71.116620
YALE         0.0            3443.0       2221.5  42.299333 -71.107678
YARMOUTH     0.0            1636.0       1227.0  42.345797 -71.076897
YAWKEY       0.0           19077.5      11257.0  42.346066 -71.098869
YEOMAN       0.0               0.0          0.0  42.330043 -71.075778
YORK         0.0            6759.0       4280.5  42.299691 -71.080724
YORKTOWN     0.0            2276.0       1416.0  42.285452 -71.162691
YOUNGS       0.0               0.0          0.0  42.270430 -71.096660
YUILL        0.0               0.0          0.0  42.237427 -71.130452
ZAMORA       0.0            4138.0       2540.0  42.322413 -71.113177
             425.0             0.0          0.0  42.322341 -71.113634
ZEIGLER      0.0            2106.0       1384.5  42.329004 -71.081430
             1.0            3576.0       2384.0  42.328853 -71.079684
ZELLER       0.0            2590.5       1494.5  42.291995 -71.136578

[5430 rows x 13 columns]

In [13]:
bos_st_count = bos_street_group.count()

In [44]:
bos_st_count.head()

                   PID  ST_NUM  STNum_nospace  STNum_noLetters  ST_NAME_SUF  \
ST_NAME block_set
A       0.0         26      26             18               26           26
        1.0          6       6              6                6            6
        2.0          3       3              3                3            3
        3.0          4       4              4                4            4
ABBOT   0.0         27      27             27               27           27

                   ZIPCODE  PTYPE  LU  OWN_OCC  AV_LAND  AV_BLDG  LAND_SF  \
ST_NAME block_set
A       0.0             26     26  26       26       26       26       26
        1.0              6      6   6        6        6        6        6
        2.0              3      3   3        3        3        3        3
        3.0              4      4   4        4        4        4        4
ABBOT   0.0             27     27  27       27       27       27       27

                   YR_BUILT  YR_REMOD  GROSS_AREA  LIVING_AREA  LATITUDE  \
ST_NAME block_set
A       0.0              25         5          23           23        26
        1.0               6         0           6            6         6
        2.0               3         1           3            3         3
        3.0               4         4           4            4         4
ABBOT   0.0              27        21          27           27        27

                   LONGITUDE
ST_NAME block_set
A       0.0               26
        1.0                6
        2.0                3
        3.0                4
ABBOT   0.0               27